<?php

namespace TestBundle\Repository;


use Doctrine\ORM\Query;
/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c.name
                FROM TestBundle:City c
                WHERE c.name LIKE :str'
            )
            ->setParameter('str', $str.'%')
            ->getResult();
    }
}
