<?php

namespace TestBundle\Repository;


use TestBundle\Entity\Rubrika;
use Doctrine\ORM\Query;

/**
 * RubrikaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubrikaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.column1
                FROM TestBundle:Rubrika r
                WHERE r.column1 LIKE :str'
            )
            ->setMaxResults(10)
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
